services:
  postgres:
    image: postgres:18
    container_name: postgres-sql-practice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_practice
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_sql_practice:/var/lib/postgresql

volumes:
  postgres_sql_practice:
